server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Hangman
    username: root
    password: admin
  banner:
    location: classpath:banner.txt
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baselineOnMigrate: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html